<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CreateDistrictSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('districts')->delete();
        
        DB::table('districts')->insert(array (
            0 => 
            array (
                'dist_id' => 1,
                'dist_pro_id' => 6,
                'dist_name_en' => 'Ampara',
                'dist_name_si' => 'අම්පාර',
                'dist_name_ta' => 'அம்பாறை',
                'dist_isActive' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            1 => 
            array (
                'dist_id' => 2,
                'dist_pro_id' => 8,
                'dist_name_en' => 'Anuradhapura',
                'dist_name_si' => 'අනුරාධපුරය',
                'dist_name_ta' => 'அனுராதபுரம்',
                'dist_isActive' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            2 => 
            array (
                'dist_id' => 3,
                'dist_pro_id' => 7,
                'dist_name_en' => 'Badulla',
                'dist_name_si' => 'බදුල්ල',
                'dist_name_ta' => 'பதுளை',
                'dist_isActive' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            3 => 
            array (
                'dist_id' => 4,
                'dist_pro_id' => 6,
                'dist_name_en' => 'Batticaloa',
                'dist_name_si' => 'මඩකලපුව',
                'dist_name_ta' => 'மட்டக்களப்பு',
                'dist_isActive' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            4 => 
            array (
                'dist_id' => 5,
                'dist_pro_id' => 1,
                'dist_name_en' => 'Colombo',
                'dist_name_si' => 'කොළඹ',
                'dist_name_ta' => 'கொழும்பு',
                'dist_isActive' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            5 => 
            array (
                'dist_id' => 6,
                'dist_pro_id' => 3,
                'dist_name_en' => 'Galle',
                'dist_name_si' => 'ගාල්ල',
                'dist_name_ta' => 'காலி',
                'dist_isActive' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            6 => 
            array (
                'dist_id' => 7,
                'dist_pro_id' => 1,
                'dist_name_en' => 'Gampaha',
                'dist_name_si' => 'ගම්පහ',
                'dist_name_ta' => 'கம்பஹா',
                'dist_isActive' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            7 => 
            array (
                'dist_id' => 8,
                'dist_pro_id' => 3,
                'dist_name_en' => 'Hambantota',
                'dist_name_si' => 'හම්බන්තොට',
                'dist_name_ta' => 'அம்பாந்தோட்டை',
                'dist_isActive' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            8 => 
            array (
                'dist_id' => 9,
                'dist_pro_id' => 9,
                'dist_name_en' => 'Jaffna',
                'dist_name_si' => 'යාපනය',
                'dist_name_ta' => 'யாழ்ப்பாணம்',
                'dist_isActive' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            9 => 
            array (
                'dist_id' => 10,
                'dist_pro_id' => 1,
                'dist_name_en' => 'Kalutara',
                'dist_name_si' => 'කළුතර',
                'dist_name_ta' => 'களுத்துறை',
                'dist_isActive' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            10 => 
            array (
                'dist_id' => 11,
                'dist_pro_id' => 2,
                'dist_name_en' => 'Kandy',
                'dist_name_si' => 'මහනුවර',
                'dist_name_ta' => 'கண்டி',
                'dist_isActive' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            11 => 
            array (
                'dist_id' => 12,
                'dist_pro_id' => 5,
                'dist_name_en' => 'Kegalle',
                'dist_name_si' => 'කෑගල්ල',
                'dist_name_ta' => 'கேகாலை',
                'dist_isActive' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            12 => 
            array (
                'dist_id' => 13,
                'dist_pro_id' => 9,
                'dist_name_en' => 'Kilinochchi',
                'dist_name_si' => 'කිලිනොච්චිය',
                'dist_name_ta' => 'கிளிநொச்சி',
                'dist_isActive' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            13 => 
            array (
                'dist_id' => 14,
                'dist_pro_id' => 4,
                'dist_name_en' => 'Kurunegala',
                'dist_name_si' => 'කුරුණෑගල',
                'dist_name_ta' => 'குருணாகல்',
                'dist_isActive' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            14 => 
            array (
                'dist_id' => 15,
                'dist_pro_id' => 9,
                'dist_name_en' => 'Mannar',
                'dist_name_si' => 'මන්නාරම',
                'dist_name_ta' => 'மன்னார்',
                'dist_isActive' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            15 => 
            array (
                'dist_id' => 16,
                'dist_pro_id' => 2,
                'dist_name_en' => 'Matale',
                'dist_name_si' => 'මාතලේ',
                'dist_name_ta' => 'மாத்தளை',
                'dist_isActive' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            16 => 
            array (
                'dist_id' => 17,
                'dist_pro_id' => 3,
                'dist_name_en' => 'Matara',
                'dist_name_si' => 'මාතර',
                'dist_name_ta' => 'மாத்தறை',
                'dist_isActive' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            17 => 
            array (
                'dist_id' => 18,
                'dist_pro_id' => 7,
                'dist_name_en' => 'Monaragala',
                'dist_name_si' => 'මොණරාගල',
                'dist_name_ta' => 'மொணராகலை',
                'dist_isActive' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            18 => 
            array (
                'dist_id' => 19,
                'dist_pro_id' => 9,
                'dist_name_en' => 'Mullaitivu',
                'dist_name_si' => 'මුලතිව්',
                'dist_name_ta' => 'முல்லைத்தீவு',
                'dist_isActive' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            19 => 
            array (
                'dist_id' => 20,
                'dist_pro_id' => 2,
                'dist_name_en' => 'Nuwara Eliya',
                'dist_name_si' => 'නුවර එළිය',
                'dist_name_ta' => 'நுவரேலியா',
                'dist_isActive' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            20 => 
            array (
                'dist_id' => 21,
                'dist_pro_id' => 8,
                'dist_name_en' => 'Polonnaruwa',
                'dist_name_si' => 'පොළොන්නරුව',
                'dist_name_ta' => 'பொலன்னறுவை',
                'dist_isActive' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            21 => 
            array (
                'dist_id' => 22,
                'dist_pro_id' => 4,
                'dist_name_en' => 'Puttalam',
                'dist_name_si' => 'පුත්තලම',
                'dist_name_ta' => 'புத்தளம்',
                'dist_isActive' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            22 => 
            array (
                'dist_id' => 23,
                'dist_pro_id' => 5,
                'dist_name_en' => 'Ratnapura',
                'dist_name_si' => 'රත්නපුර',
                'dist_name_ta' => 'இரத்தினபுரி',
                'dist_isActive' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            23 => 
            array (
                'dist_id' => 24,
                'dist_pro_id' => 6,
                'dist_name_en' => 'Trincomalee',
                'dist_name_si' => 'ත්‍රිකුණාමලය',
                'dist_name_ta' => 'திருகோணமலை',
                'dist_isActive' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
            24 => 
            array (
                'dist_id' => 25,
                'dist_pro_id' => 9,
                'dist_name_en' => 'Vavuniya',
                'dist_name_si' => 'වව්නියාව',
                'dist_name_ta' => 'வவுனியா',
                'dist_isActive' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'created_by' => NULL,
                'updated_by' => NULL,
                'deleted_by' => NULL,
            ),
        ));

    }
}
